name: Destroy Lab 3 AWS Resources

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS Region where resources are deployed'
        required: true
        default: 'us-west-2'
        type: choice
        options:
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
          - eu-west-1
          - eu-central-1
          - ap-northeast-1
          - ap-southeast-1
          - ap-southeast-2
      confirmation:
        description: 'Type "destroy" to confirm deletion of all AWS resources'
        required: true
        type: string

env:
  TF_WORKING_DIR: ./lab03-aws-cloud-deployment/terraform

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirmation == 'destroy' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -auto-approve -var="aws_region=${{ github.event.inputs.aws_region }}" -var="github_repository=${{ github.repository }}"

      - name: Cleanup Confirmation
        run: |
          echo "✅ All AWS resources have been destroyed successfully."
          echo "Your AWS account should no longer incur charges for Lab 3 resources."
